language: python
python: '3.6'
script: nosetests
install: pip install --user -r requirements.txt
deploy:
  provider: pages
  skip_cleanup: true
  github_token: b06c8c5b47cb9b03c7f24cf6e1f8cacff7601201
  on:
    branch: master
after_success: coveralls
